# Generated by Django 4.1.2 on 2022-12-13 00:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('choji_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='choji_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='following',
            name='choji_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='choji_code',
            field=models.CharField(default='970b4f773bc14852b0b6e9e259995b83', max_length=2083),
        ),
        migrations.AlterField(
            model_name='group_account',
            name='choji_code',
            field=models.CharField(default='9fa2b3bae2774c07bd2b1dfab7a4d790', max_length=2083),
        ),
        migrations.AlterField(
            model_name='group_chat',
            name='choji_code',
            field=models.CharField(default='e8440183716a4ddd95d792bcded4357d', max_length=2083),
        ),
        migrations.AlterField(
            model_name='trade',
            name='choji_code',
            field=models.CharField(default='bd3fdbe97fbd4f5eba8e9fb8f5f303ea', max_length=2083),
        ),
    ]
